In [1]:
import torch
import os
import pandas as pd
from utils import extract_features

In [2]:
print(f"Is CUDA available? {torch.cuda.is_available()}")
print(f"GPU Name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

Is CUDA available? True
GPU Name: NVIDIA GeForce RTX 3050 Laptop GPU

In [3]:
features = []
labels = []

In [4]:
for label in ['NORMAL', 'PNEUMONIA']:
    folder = os.path.join('chest_xray/train/', label)
    for file in os.listdir(folder):
        if not file.endswith(".jpeg"):
            continue
        img_path = folder + '/' + file
        feat = extract_features(img_path)
        features.append(feat)
        labels.append(label)

In [5]:
df_f_train = pd.DataFrame(features)
df_l_train = pd.DataFrame(labels)

df_train = pd.merge(df_f_train, df_l_train, left_index=True, right_index=True)

In [6]:
df_train.head()

,0_x,1,2,3,4,5,6,7,8,9,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,0_y
0,-0.000286,0.006203,0.002035,0.001476,-0.138594,-0.522918,-0.000491,-0.000854,0.261322,0.000066,...,0.616742,0.096130,1.684341,1.455542,0.254155,-0.246374,2.074667,1.175730,-0.255693,NORMAL
1,-0.000048,0.008297,0.000642,0.002412,-0.109568,-0.397811,-0.000634,0.000038,0.181377,0.000133,...,0.681944,-0.664893,0.348052,5.252523,0.716616,-0.350921,1.075666,0.410156,-0.742168,NORMAL
2,-0.000226,0.005358,0.003730,0.001862,-0.133520,-0.295022,-0.000861,-0.000248,0.181222,0.000193,...,0.037045,-0.255567,1.697353,4.746704,0.545553,0.067992,2.255845,1.485110,-0.437690,NORMAL
3,-0.000157,0.005601,0.004333,0.002208,-0.190418,-0.126509,-0.000539,0.000664,0.165036,0.000254,...,1.105227,0.102026,1.083612,7.410175,0.185537,-0.211293,0.977330,0.165981,-0.540183,NORMAL
4,-0.000074,0.002661,0.001165,0.003077,-0.117278,-0.416737,-0.001142,0.000885,0.107689,0.000041,...,0.572365,0.625211,1.245083,4.199072,0.635340,-0.241166,0.866986,0.235723,-0.590647,NORMAL

In [7]:
df_train['0_y'].value_counts()

0_y
PNEUMONIA    3875
NORMAL       1341
Name: count, dtype: int64

In [8]:
df_train['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)
df_train['0_y'].astype("int64")

C:\Users\HP\AppData\Local\Temp\ipykernel_17168\157240186.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_17168\157240186.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)

0       0
1       0
2       0
3       0
4       0
       ..
5211    1
5212    1
5213    1
5214    1
5215    1
Name: 0_y, Length: 5216, dtype: int64

In [9]:
features = []
labels = []
for label in ['NORMAL', 'PNEUMONIA']:
    folder = os.path.join('chest_xray/val/', label)
    for file in os.listdir(folder):
        if not file.endswith(".jpeg"):
            continue
        img_path = folder + '/' + file
        feat = extract_features(img_path)
        features.append(feat)
        labels.append(label)

In [10]:
df_f_val = pd.DataFrame(features)
df_l_val = pd.DataFrame(labels)

df_val = pd.merge(df_f_val, df_l_val, left_index=True, right_index=True)

In [11]:
df_val.head()

,0_x,1,2,3,4,5,6,7,8,9,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,0_y
0,-0.000211,0.004906,0.001502,0.001453,-0.060594,-0.406660,-0.000961,0.000028,0.161204,0.000102,...,0.911682,-0.422242,1.785000,3.103085,0.629148,-0.509794,2.479641,0.674825,-1.112991,NORMAL
1,-0.000480,0.005785,0.002291,0.001510,-0.091534,-0.521709,-0.000450,-0.001822,0.243952,0.000115,...,1.669674,0.349629,0.808540,3.017563,1.549832,0.612679,0.372945,1.493285,-0.643484,NORMAL
2,-0.000407,0.007490,0.001800,0.001658,-0.135121,-0.274944,-0.000708,-0.001377,0.166654,0.000305,...,1.569743,-0.566043,1.041140,2.902099,0.725770,-0.087138,1.827379,1.036846,-0.744148,NORMAL
3,-0.000089,0.006230,0.002127,0.002491,-0.117464,-0.489586,-0.000927,-0.001180,0.191160,0.000104,...,1.689332,0.361594,2.053963,3.377822,0.462907,0.365512,0.888905,1.192842,-0.412291,NORMAL
4,-0.000512,0.003777,0.002978,0.001824,-0.114673,-0.562573,-0.000578,-0.001836,0.037120,0.000098,...,1.210933,0.813857,2.988388,1.769681,-0.466753,-0.341730,1.382939,0.987402,-0.622765,NORMAL

In [12]:
df_val.shape

(16, 1025)

In [13]:
df_val['0_y'].value_counts()
df_val['0_y']

0        NORMAL
1        NORMAL
2        NORMAL
3        NORMAL
4        NORMAL
5        NORMAL
6        NORMAL
7        NORMAL
8     PNEUMONIA
9     PNEUMONIA
10    PNEUMONIA
11    PNEUMONIA
12    PNEUMONIA
13    PNEUMONIA
14    PNEUMONIA
15    PNEUMONIA
Name: 0_y, dtype: object

In [14]:
df_val['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)
df_val['0_y'].astype("int64")

C:\Users\HP\AppData\Local\Temp\ipykernel_17168\1780585898.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_val['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: 0_y, dtype: int64

In [15]:
features = []
labels = []
for label in ['NORMAL', 'PNEUMONIA']:
    folder = os.path.join('chest_xray/test/', label)
    for file in os.listdir(folder):
        if not file.endswith(".jpeg"):
            continue
        img_path = folder + '/' + file
        feat = extract_features(img_path)
        features.append(feat)
        labels.append(label)

In [16]:
df_f_test = pd.DataFrame(features)
df_l_test = pd.DataFrame(labels)

df_test = pd.merge(df_f_test, df_l_test, left_index=True, right_index=True)

In [17]:
df_test.head()

,0_x,1,2,3,4,5,6,7,8,9,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,0_y
0,-0.000217,0.005303,-0.000342,0.001054,-0.078457,-0.391258,-0.000593,0.000460,0.295700,0.000200,...,1.095526,-0.035729,0.931914,4.013433,1.912549,0.322573,0.634234,0.474985,-0.079320,NORMAL
1,-0.000110,0.009837,0.002414,0.000999,-0.016209,-0.384812,-0.000924,-0.000138,0.250690,0.000365,...,0.857677,-0.226157,1.832867,6.274942,1.349737,-0.116144,2.652224,0.272118,-0.142810,NORMAL
2,-0.000044,0.005828,0.000777,0.001437,-0.186046,-0.219535,-0.001028,-0.000495,0.158731,-0.000010,...,1.103356,0.338695,0.714376,2.886412,0.121505,-0.182210,0.560833,0.796840,-0.168721,NORMAL
3,-0.000247,0.011074,-0.001070,0.001387,-0.020836,-0.030355,-0.000661,-0.001341,0.141247,-0.000010,...,0.515468,-0.803456,-0.257485,4.759460,1.202152,-0.285173,2.730608,-0.031961,-0.343730,NORMAL
4,-0.000255,0.009803,0.000337,0.001887,-0.134981,-0.170257,-0.000849,-0.002151,0.217365,0.000101,...,2.287298,-0.539222,0.826852,4.347828,-0.070516,-0.201856,3.173863,0.315158,-0.597293,NORMAL

In [18]:
df_test.shape

(624, 1025)

In [19]:
df_test['0_y'].value_counts()

0_y
PNEUMONIA    390
NORMAL       234
Name: count, dtype: int64

In [20]:
df_test['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)
df_test['0_y'].astype("int64")

C:\Users\HP\AppData\Local\Temp\ipykernel_17168\3831899217.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_17168\3831899217.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test['0_y'].replace({'NORMAL': 0, 'PNEUMONIA': 1}, inplace=True)

0      0
1      0
2      0
3      0
4      0
      ..
619    1
620    1
621    1
622    1
623    1
Name: 0_y, Length: 624, dtype: int64

In [21]:
df_val.to_csv('validation_dataset.csv', index=False)

In [22]:
df_test.to_csv('test_dataset.csv', index=False)

In [23]:
df_train.to_csv('train_dataset.csv', index=False)